### ISSUE TITLE
Strings also have length

### ISSUE THREAD

**Issue by homm** [bfred-it/image-promise#1]
`loadImage( '/cat.jpg' );` leads ot Maximum call stack size exceeded because of `'/cat.jpg'` is a string with length 8 which is treated as array, where the first element is a string `'/'` with length 1 which is treated as array, where the first element is a string `'/'` with length 1 which is treated as array, where the first element is a string `'/'` with length 1 which is treated as array, where the first element is a string `'/'` with length 1 which is treated as array, where the first element is a string `'/'` with length 1 which is treated as array, where the first element is a string `'/'` with length 1 which is treated as array, where the first element is a string `'/'` with length 1 which is treated as array, where the first element is a string `'/'` with length 1 which is treated as array, where the first element is a string `'/'` with length 1 which is treated as array, where the first element is a string `'/'` with length 1 which is treated as array, where the first element is a string `'/'` with length 1 which is treated as array, where the first element is a string `'/'` with length 1 which is treated as array, where the first element is a string `'/'` with length 1 which is treated as array, where the first element is a string `'/'` with length 1

**Comment by bfred-it** [comment]
Fuuuuuuuuuuuuuuu I played around a lot with that detection and of course I screwed up.

**Comment by bfred-it** [comment]
Let me know if this fixed it for you

**Comment by homm** [comment]
I fixed it on my side with $.isArray() because I already used jQuery.

**Comment by bfred-it** [comment]
It's not equivalent though; $.isArray() only works with literal arrays, it doesn't detect `document.querySelectorAll('img)` nor `$('img')` itself. image-promise should handle all those situations now
