### ISSUE TITLE
Doesn't work correctly with cached images in IE11

### ISSUE THREAD

**Issue by englishextra** [bfred-it/image-promise#10]
Of course, with Promise polyfill, ie11 throws an error in catch section of promise, but strangly returns an image.

**Comment by bfred-it** [comment]
You're saying that this is what's happening:

```js
imagePromise('image.jpg').catch(function (img) {
   console.log(img); // <img src='...'>
});

**Comment by englishextra** [comment]
I had:
```
				/* if (w.Promise) {
					imagePromise(_src).then(function (r) {
						e.src = _src;
						console.log("manageDataSrcImg => imagePromise: loaded image:", r);
					}).catch (function (err) {
						console.log("manageDataSrcImg => imagePromise: cannot load image:", err);
					});
				} else {
					e.src = _src;
				} */
				e.src = _src;
```

**Comment by bfred-it** [comment]
I don't understand what caused you to remove that code

**Comment by englishextra** [comment]
Because IE11 loads image randomly. Sometimes it does, sometimes it won't. Other browsers behave OK.

**Comment by bfred-it** [comment]
This seems to work correctly for me: https://jsbin.com/xocivegetu/1/edit?html,js,output

**Comment by bfred-it** [comment]
Also an example with multiple successful loads: 

<a href="https://jsbin.com/veneduxizi/1/edit?js,output"><img width="692" alt="google chrome_github com_screen shot 2017-04-29 20 28 54" src="https://cloud.githubusercontent.com/assets/1402241/25555189/801cc54a-2d1a-11e7-92f6-0faf5b9ad561.png"></a>

**Comment by englishextra** [comment]
Perhaps it's a polyfill to blame, in my case:
https://github.com/taylorhakes/promise-polyfill

**Comment by yvt** [comment]
It appears that IE (and possibly Edge?) occasionally sets `image.complete` to `true` before updating the value of `image.naturalWidth`, causing this library to misdetect successfully loaded images as corrupted. This becomes apparent when the image is already in the browser's cache and you check these values immediately (without emptying the call stack and completing the current (micro)task) after setting the value of `image.src`.

<img width="831" alt="screen shot 2017-12-26 at 21 51 13" src="https://user-images.githubusercontent.com/5253988/34357087-70711c56-ea87-11e7-837b-0df0541d40e7.png">

I suggest checking `image.naturalWidth` asynchronously. I mean:

```js
const Promise = Promise.resolve().then(() => 
    new Promise((resolve, reject) => {
        if (image.naturalWidth) {
            resolve(image):
        }  else if (image.complete) {
            reject(image);
        }
        /* ... */
    })
});
```

**Comment by bfred-it** [comment]
Thanks fo @yvt! Can you verify if checking that way consistently solves it? For example when loading a huge image (like 4000x4000) because I'm thinking that, while the network activity is `complete`, IE takes further time to actually parse the image. Is this time consistently a _tick_ or do we need a `setInterval` to check for it until it's done?

**Comment by yvt** [comment]
[It appears to be so.](https://jsbin.com/vubozo/15/edit?js,console,output) Also I ran a test code similar to this one for > 5000 times and it went perfectly.

Note that decoding of the image data takes place as a separate step from that of the metadata, and might be deferred until the image is actually displayed on the screen. There is [a proposal to add a method named `decode`](https://github.com/whatwg/html/issues/1920) that enforces the decoding of the image.

**Comment by bfred-it** [comment]
I applied your suggestion in #13, can you try its `index.js`?

**Comment by bfred-it** [comment]
Sorry that this didn't get fixed in time. But now IE and EdgeHTML are over
