### ISSUE TITLE
Loading percent

### ISSUE THREAD

**Issue by clecocq** [bfred-it/image-promise#11]
Hi,

Great code, I wonder how we could set a loading percent / progression using your code?

Thank you in advance,

Cyril

**Comment by bfred-it** [comment]
With this you can only know when a whole image has been loaded, so no progress if you only load one image. 

You can write some code to keep track of multiple images loading and increase the percentage every time an image finishes loading. 

Full-progress is only possible if you load images via XHR2, but `image-promise` only used `<img>`

**Comment by bfred-it** [comment]
Here you go! https://github.com/sindresorhus/p-progress

```js
const imagesLoading = PProgress.all([
	loadImage('1.jpg'),
	loadImage('2.jpg'),
	loadImage('3.jpg'),
	loadImage('4.jpg')
]);

imagesLoading.onProgress(console.log);
// log: 0.25
// log: 0.5
// log: 0.75
// log: 1

imagesLoading.then(console.log);
// log: [<img>, <img>, <img>, <img>]
```
