### ISSUE TITLE
Provide ES Module version via "module" field

### ISSUE THREAD

**Issue by niksy** [bfred-it/image-promise#18]
This package is shipped if ES Modules version (`image-promise.es-modules.js`) but it isn’t referenced anywhere so bundling tools like Webpack assume that only Common JS version is available since it’s references in `main` field. Would you consider adding `module` filed which references ES Modules version? I can make PR for this!

**Comment by bfred-it** [comment]
This is intentional
https://github.com/bfred-it/image-promise/commit/db3250f7f4feb7730a35321efd7e3281457efc2c
https://github.com/webpack/webpack/issues/4742
