### ISSUE TITLE
Deprecate package

### ISSUE THREAD

**Issue by fregante** [bfred-it/image-promise#27]
After finishing https://github.com/fregante/image-promise/pull/25, I decided this package doesn't make sense anymore because of a new API: [image.decode()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decode)

```diff
// preload image
- loadImage(url)
+ img = new Image()
+ img.src = src

// load and await image
- await loadImage(url)
+ img = new Image()
+ img.src = src
+ await img.decode()
```

Any reason for this module to continue existing? Its utility is mainly around the ability to create images from strings _and_ await them:

```js
await loadImages([a,b,c])
```

But that's not a great API if one of the loading fails, you might want to implement your own retry mechanism or just ignore them. Instead the whole promise fails.

So should it just return an array and have you deal with them via `Promise.allSettled()`? At that point the advantage is minimal, and not really matching the package name.

```diff
- const promises = loadImages([a,b,c])
+ const images = [a,b,c].map(url => {
+ 	img = new Image(URL);
+ 	img.src = url;
+ 	return img;
+ })

**Comment by fregante** [comment]
Yep

**Comment by fisker** [comment]
```js
await Object.assign(new Image(), {src: url}).decode()
```

**Comment by fregante** [comment]
That's fine only if you want to preload the image, because unfortunately .decode() returns `Promise<void>`

**Comment by fregante** [comment]
Oh right. So weird that it accepts the size and not the source 🤷‍♂️
