### ISSUE TITLE
Feature request: browserstack tests

### ISSUE THREAD

**Issue by jantimon** [bfred-it/image-promise#3]
Ally.js uses browserstack (free for open source) to test the library against a bunch of browsers:

https://github.com/medialize/ally.js/blob/master/test/browserstack.js#L24-L72

This might be also quite useful to guarantee a browser matrix

**Comment by bfred-it** [comment]
It _would_ be nice but I'm not familiar with browser testing setup. PRs welcome

**Comment by jantimon** [comment]
See #5
