### ISSUE TITLE
Feature request: Ignore broken images

### ISSUE THREAD

**Issue by jantimon** [bfred-it/image-promise#4]
In some cases we are only interested if images are still loading or not so it would be cool if you would allow to wait for all images to be finished (even if some of them are broken).

**Comment by bfred-it** [comment]
I assume you're referring to `loadImage([/*array*/])`

Even if one fails, all the images complete the loading (although, yes, their `<img>`s) are lost. The default behavior in that case matches `Promise.all()`

You can achieve this behavior by looping your own array, similarly to how I do it:

```js
const images = [/*array*/].map(loadImages);
```

**Comment by jantimon** [comment]
Would be cool if there were a flag like `loadImages([array], { ignoreBroken: true })`

**Comment by bfred-it** [comment]
But that'd add a lot of complexity for something you can do with two lines externally.

You can even wrap it up and avoid pSettle:

```js
function loadButIgnore(array) {
    return array.map(img => loadImages(img).catch(img => img));
}
```

**Comment by jantimon** [comment]
I guess this a common use case and similar image load libraries also support it.
In which situations would you like to have a break early?

If I would have to write my own utility function to use a utility function it would be easier just to copy most of the image-promise code instead of using the module.

**Comment by bfred-it** [comment]
How do you handle that output though? What is the use of having a `Promise.all` be fulfilled if some images failed loading? If you are going to check if each image has loaded, you might as well implement that custom behavior.

What I'm thinking, perhaps, is to return a plain array of Promises that you can handle autonomously, if the standard [fail-fast behavior of `Promise.all`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all#Promise.all_fail-fast_behaviour) doesn't fit your needs.

**Comment by bfred-it** [comment]
> If I would have to write my own utility function to use a utility function it would be easier just to copy most of the image-promise code instead of using the module.

That's your prerogative. The point of using 3rd-party modules is to avoid managing your own files. As explained earlier you can use `p-settle` inline and avoid creating anything else.

I gave it a try and this was the best I could come up with, but I still cannot make sense of it resolving while something inside actually fails.

<img width="601" alt="screen shot 2017-03-01 at 00 25 33" src="https://cloud.githubusercontent.com/assets/1402241/23416530/06133222-fd98-11e6-9fb2-2aea4e3321bb.png">

The mechanism to check if each image in the resulting promise has resolved, would give `image-promise` even less sense:

loadImages(images).then(images => {
  images.forEach(img => {
    if (img.complete && img.naturalWidth) {
      // loaded
    } else {
      // errored
    }
  })
})

**Comment by jantimon** [comment]
Added in #5 - still 312kb

**Comment by bfred-it** [comment]
As mentioned this will not be added. Your PR breaks this: `array.map(loadImage)`

**Comment by jantimon** [comment]
Why would it break that?

**Comment by bfred-it** [comment]
`array.map` passes calls `loadImage` as `loadImage(element, index)`, where index is 0, 1, 2, etc. 

IP currently ignores the second parameter. Your PR will consider any elements past 0 as `ignoreBroken`

**Comment by jantimon** [comment]
that's very true - we should definitely add some more unit tests to check for stuff like that ;)

What about `ignoreBroken === true ? ` this would also work in this case

**Comment by bfred-it** [comment]
I still don't see the need for this as outlined in https://github.com/bfred-it/image-promise/issues/4#issuecomment-283107919

**Comment by jantimon** [comment]
Alright thanks for your time anyway 👍

**Comment by jantimon** [comment]
I guess it would be much easier to release a new version of image promise to npm with full test coverage, typescript typings and the ignoreBroken image feature so people can stay with image-promise1 for the old feature and if they need a more solid version they can upgrade to the new one

**Comment by bfred-it** [comment]
I understand that your needs may differ from mine, but I asked multiple times for an explanation and you didn't give me one. I asked a question on the typings and you didn't answer.

Also I showed how you could get the same result by using p-settle or another one-liner but instead you skipped my questions and went ahead sending a PR with unrelated changes. Everything you changed was made that way because it resulted in a smaller size.

Tests and typings are welcome, but lack is discussion and unrelated changes aren't

**Comment by jantimon** [comment]
We use image-promise for ensuring that the ajax result is ready to be measured:


```
// Pseudo code
fetch(url)
  .then((result) => {
     target.innerHTML = result;
     return imagePromise(target.querySelectorAll('img'));
  })
  .then(() => {
     // Fancy bootstrap
  });
```

If you see the code above it might cause that if any of the images are broken our entire ajax code breaks just because one of the images is not visible.

I understand your solution with `p-settle` however every dependency which we add to our quite huge project adds a new responsibility and we prefer to pick small robust libraries which do one thing and do it well (good test coverage, easy solution).
That's why we chose image-promise in the first place.

**Comment by bfred-it** [comment]
**Typings:** 4051fb0075b7c2b858033a9385c323a705aa571b actually _saves_ the user from uncaught errors (e.g. `undefined.length` or `2.addEventListener`), which you made me think about. It was only complementary to the typings.

My question was more about whether your typings still allowed a typescript user to pass Array-likes. From your answer it sounds they don't, therefore the typings were incomplete.

**Ignoring the results:** Thanks for your snippet! It's actually easier than I even thought:

```patch
// Pseudo code
fetch(url)
  .then((result) => {
     target.innerHTML = result;
-     return imagePromise(target.querySelectorAll('img'));
+     return imagePromise(target.querySelectorAll('img')).catch(noop);
  })
  .then(() => {
     // Fancy bootstrap
  });
```

Nothing needed, literally one more function call

**Comment by jantimon** [comment]
Exactly that would be a very nice solution and I would go with it right away but there is this fail-fast behavior of Promise.all which would not allow such a simple solution - right?

**Comment by bfred-it** [comment]
Right right, my bad, I hit send too soon

**Comment by jantimon** [comment]
Regarding the typings

Don't get me wrong 4051fb0 is not bad but actually all what it does (when used with your Promise.all feature) is turning a Promise.reject with an error message (cant read length of undefined) into a Promise.reject without an error message... so no big gain.

It would still allow you to use jQuery Elements or NodeLists but you would have to declare that those arrays contain only images:

```js
await imagePromise(<HTMLImageElement[]>target.querySelectorAll('img'));
```

```js
imagePromise(<HTMLImageElement[]>target.querySelectorAll('img')).then(() => ...);
```

**Comment by bfred-it** [comment]
`loadImage()` is not run entirely inside a promise, so pre-4051fb0 `loadImage(1)` would have thrown an error [here](https://github.com/bfred-it/image-promise/blob/237dde038e26789fe429d7ec19a808f93d62082e/index.js#L7) — which makes me think that maybe it should be wholly inside `new Promise(...)`

Ok, good to know. I'm not familiar with TypeScript so I wanted to make sure that there was a way to do it.
